### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by ooxi** [javadelight/delight-fileupload#1]
Hi,

could you please publish to Maven Central? I'd like to use your package but depending on something not available in Maven Central is hard.

-- ooxi

**Comment by mxro** [comment]
Thank you for your message!

Yes, I think it would be great to publish this into Maven Central. But I think that is not so easy to do. Have you ever done this and have some pointers?

Otherwise, it should work with this repository for now:

```
<repositories>
		<repository>
			<id>Appjangle Releases</id>
			<url>http://maven.appjangle.com/appjangle/releases</url>
		</repository>
</repositories>
```

**Comment by ooxi** [comment]
I thought about using *Appjangle Releases* but I cannot find *delight-fileupload* in the [directory listing](http://maven.appjangle.com/appjangle/releases/org/javadelight/). Maybe it was never published as release, only as snapshot?

I [have published to Maven Central](https://mvnrepository.com/artifact/com.github.ooxi/jdatauri/1.0) and it's a pain in the behind :-( I'll look around maybe I can find a simple way, but you'd do me a favour if you could check the publication to Appjangle

**Comment by mxro** [comment]
Yeah, I figured the Maven Central deployment might be difficult - any additional pointers you have will be most welcome!

And, yes, the artifact was missing from the repository. I have uploaded it now!

```
  <groupId>org.javadelight</groupId>
  <artifactId>delight-fileupload</artifactId>
  <version>0.0.2</version>
```

**Comment by javadelight** [comment]
This is now on Maven Central.

https://search.maven.org/#search%7Cga%7C1%7Cdelight-fileupload

I deployed it using BinTray. It wasn't all that difficult in the end!

**Comment by ooxi** [comment]
Nice, could you tell me how you did it? I thought BinTray was pushing JFrog as Maven Central alternative.

**Comment by mxro** [comment]
I basically just followed the instructions JFrog has provided:

https://bintray.com/docs/usermanual/uploads/uploads_syncingwiththirdpartyplatforms.html

In addition, you can specify a GPG key for automatic signing of the artifacts (very handy). So I upload them to BinTray unsigned and BinTray does the signing them before they go into central.
