### ISSUE TITLE
HttpServletRequest not found

### ISSUE THREAD

**Issue by kovsharov** [javadelight/delight-fileupload#3]
Hi, I am facing some problem using this library. 
I just add Maven dependency as was shown in my empty project and I tried to call `FileUpload.parse(data, contentType)`. But I got an error ` java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest` which is caused by `java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest`

I am using `0.0.4` version.

Could you please explain where is the error?

**Comment by mxro** [comment]
Hello! Maybe you are missing the servlet api dependency: https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api/4.0.1

Does adding that resolve the issue?

**Comment by kovsharov** [comment]
> Hello! Maybe you are missing the servlet api dependency: https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api/4.0.1
> 
> Does adding that resolve the issue?

That was the first thing I did in order to resolve my issue. But the error is still appears.
By the way I've tested it with two different systems and I still have the error.

**Comment by mxro** [comment]
Sorry for the late reply!

I have made a few changes to the project (changed dependencies and added a unit test) and released the new version 0.0.5. Does that work better for you?

Did you see the project is being built and tested on Travis CI. It seems to work there. Maybe you could double check your setup against the environment Travis CI uses to run it:

https://travis-ci.org/javadelight/delight-fileupload

**Comment by kovsharov** [comment]
Ok, I guess something wrong with my environment.
Thank you!
